version: "3.8"
services:
  backend:
    build: ./back-end
    image: dzestate-backend-image
    container_name: dzestate-backend-container
    ports:
      - "3005:3005"
    restart: always
    env_file:
      - back-end/.env
  frontend:
    build: ./front-end
    image: dzestate-frontend-image
    container_name: dzestate-frontend-container
    ports:
      - "4002:4002"
    restart: always
    env_file:
      - front-end/.env
